# Generated by Django 5.1.6 on 2025-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/'),
        ),
    ]
